# Gaussian Elimination as an iterative algorithm

- pick a pivot (i,j)
- form the pivot approx from the row and column of A
- $A_{ij}$ is the classic GE pivot
- pivot approx $A_1$ is a rank 1 approximation of A
- repeat on $A - A_1$, and let the rank 2 approx be $A_2 = A_1 + row \cdot col^T/p$, where p is the pivot
- this generally knocks out the row and column, we repeat on the submatrix

In [1]:
import numpy as np
A = np.random.randn(3,3)
A

array([[ 0.43712774,  0.36691359, -2.23756711],
       [-2.13664025, -1.26058789,  0.58396303],
       [-0.86094055, -0.5603501 , -1.14472099]])

In [6]:
i,j = 1,2
A[:,j]

array([ 1.1894085 , -1.09075697, -0.2159103 ])

In [12]:
def pivot_approx(A,i,j):
    return np.outer(A[:,j],A[i,:])/A[i,j]

In [16]:
A2 = A - pivot_approx(A,1,1)
A2

array([[-0.18477445,  0.        , -2.06759564],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.08882789,  0.        , -1.40430126]])

In [17]:
A3 = A2 - pivot_approx(A2,0,0)
A3

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -2.39827069]])